Collect procedure names when opening a database, added dialog to list procedures as reminder.

diff --git a/gensfw b/gensfw
--- a/gensfw
+++ b/gensfw
@@ -87,7 +87,8 @@ is_dbase_open() { [ -n "${GF_DBNAME}" ]; }
 is_table_open() { [ -n "${GF_TNAME}" ]; }
 
 # This array changes when GF_DBNAME changes (from Dialog 1):
-declare -a TABLE_NAMES
+declare -a TABLE_NAMES=()
+declare -xa PROC_NAMES=()
 
 declare -a GSF_FIELD_NAMES  # Initialized when a table is selected
 declare -a GSF_FIELD_LABELS # From settings file or by using Dialog 5 (default labels)
@@ -190,6 +191,7 @@ declare -a INTERACTION_PREFERENCES_DIALOG=(
     --paned
     --tab="Tab1"
     --tab="Tab2"
+    --button "_Procedures":6
     --button "Show S_RM":4
     --button "Show S_QL":2
     --button "Cancel":1
@@ -917,6 +919,7 @@ set_dbase_name()
     TABLE_NAMES=()
     if string_in_array "$1" "${DBASE_NAMES[@]}" ; then
         GF_DBNAME="$1"
+        collect_procedure_names
         local IFS=$'\n'
         TABLE_NAMES=( $( mysql "${GF_DBNAME}" -BN -e "show tables" ) )
     else
@@ -1253,6 +1256,15 @@ show_interaction_preferences_dialog()
 
         case $exval in
             0) save_iact_choices "$name" "${result}"; break ;;
+            6)
+                # Dialog #10
+                show_procedures_dialog
+
+                # Update array for re-initialize the dialog:
+                IFS="${FSEP}"
+                meta_vals=( $( get_iact_meta_vals_str_from_result "${result}" ) )
+                list_vals=( $( get_iact_list_data_str_from_result "${result}" ) )
+                ;;
             2|4)
                 local cmd_to_call
                 local script_type
@@ -1509,6 +1521,32 @@ show_srm_globals_dialog()
     done
 }
 
+## Dialog #10
+show_procedures_dialog()
+{
+    local -i exval
+    local result
+    local -a arr
+
+    local cmd=("${YAD_COMMON_ARGS[@]}"
+               --list
+               --separator "${YSEP}"
+               --column "Procedure Name":TEXT
+               )
+
+    result=$( yad "${cmd[@]}" "${PROC_NAMES[@]}" )
+    exval=$?
+    if [ $exval -eq 0 ]; then
+        arr=( $result )
+        if [ "${#arr[@]}" -gt 0 ]; then
+            echo "${arr[0]}"
+            return 0
+        fi
+    fi
+    return 1
+}
+
+
 
 use_table_info()
 {
@@ -1525,6 +1563,8 @@ use_table_info()
     $GF_TABLE_READY_CALLBACK
 }
 
+
+
 collect_table_info()
 {
     if ! confirm_dbase_name || ! confirm_table_name ; then
@@ -1540,6 +1580,38 @@ WHERE c.TABLE_SCHEMA='${GF_DBNAME}'
 AND c.TABLE_NAME='${GF_TNAME}'"
 
     source bashmysql -s "${SEPS}" "information_schema" "${query}" -c "use_table_info"
+}
+
+update_global_proc_names_array()
+{
+    local rowstr
+    local -a row
+    local -i index=0
+    local IFS="${FSEP}"
+
+    PROC_NAMES=()
+    for rowstr in "${RESULT_ROWS[@]}"; do
+        row=( $rowstr )
+        if [ "${row[1]}" = "PROCEDURE" ]; then
+            PROC_NAMES[$(( index++ ))]="${row[0]}"
+        fi
+    done
+}
+
+collect_procedure_names()
+{
+    if ! confirm_dbase_name ; then
+        echo "SQL Injection test failed.  Attempt to set" >&2
+        echo "Database name = '${GF_DBNAME}'." >&2
+        exit 1
+    fi
+
+    query="\
+SELECT ROUTINE_NAME, ROUTINE_TYPE
+  FROM ROUTINES
+WHERE ROUTINE_SCHEMA='${GF_DBNAME}'"
+
+    source bashmysql -s "${SEPS}" "information_schema" "${query}" -c "update_global_proc_names_array"
 }
 
 table_get_index_key()
@@ -1607,6 +1679,7 @@ parse_args "$@"
 
 if is_table_open && is_dbase_open; then
     if is_gsf_open; then
+        collect_procedure_names
         if [ "$CL_CMD" = "save" ]; then
             GF_TABLE_READY_CALLBACK="auto_save"
         fi
