Added checks and warnings for missing database or table.

diff --git a/gensfw_session_procs b/gensfw_session_procs
--- a/gensfw_session_procs
+++ b/gensfw_session_procs
@@ -1,5 +1,32 @@
 #!/bin/bash
 
+MISSING_DATABASE()
+{
+    local -i result
+    local query=(
+        "SELECT COUNT(*)"
+        "FROM information_schema.SCHEMATA"
+        "WHERE SCHEMA_NAME='${database}'")
+
+    result=$(mysql -BN -e "${query[*]}" )
+
+    [ $result -eq 0 ]
+}
+
+MISSING_TABLE()
+{
+    local -i result
+    local query=(
+        "SELECT COUNT(*)"
+        "FROM information_schema.TABLES"
+        "WHERE TABLE_SCHEMA='${database}'"
+        "AND TABLE_NAME='${table}'" )
+
+    result=$(mysql -BN -e "${query[*]}" )
+
+    [ $result -eq 0 ]
+}
+
 get_source_path()
 {
     # Must include both the colon AND the space to trim
@@ -15,23 +42,34 @@ xslpath="${zpath}gensfw_session_procs.xsl"
 
 if [ $# -lt 2 ]; then
     echo >&2
+    echo "Missing parameters." >&2
     echo "Usage:" >&2
     echo "$ gensfw_session_procs [database name] [session information table name]" >&2
+    echo "Script terminated" >&2
     echo >&2
 else
     database="${1}"
     table="${2}"
 
-    declare -a aquery=(
-        "SELECT"
-        "COLUMN_NAME, DATA_TYPE, COLUMN_KEY, COLUMN_TYPE"
-        "FROM information_schema.COLUMNS"
-        "WHERE TABLE_SCHEMA='${database}'"
-        "AND TABLE_NAME='${table}'"
-    )
+    if MISSING_DATABASE; then
+        echo >&2
+        echo "Database '${database}' not found. Script terminated." >&2
+        echo >&2
+    elif MISSING_TABLE; then
+        echo >&2
+        echo "Table '${table}' not found.  Script terminated" >&2
+        echo >&2
+    else
+        declare -a aquery=(
+            "SELECT"
+            "COLUMN_NAME, DATA_TYPE, COLUMN_KEY, COLUMN_TYPE"
+            "FROM information_schema.COLUMNS"
+            "WHERE TABLE_SCHEMA='${database}'"
+            "AND TABLE_NAME='${table}'"
+        )
 
-    # mysql -X -e "${aquery[*]}"
-    mysql -X -e "${aquery[*]}" | xsltproc "${xslpath}" -
+        mysql -X -e "${aquery[*]}" | xsltproc "${xslpath}" -
+    fi
 fi
 
 
